version: '3.4'

services:
  main:
    command: ./botcannon
    build: dockerbuild/cannon/.
    volumes:
      - ./app:/home/developer/app:ro
      - ./sockets/:/run/redis/:rw
      - ./dockerbuild/cannon/botcannon/botcannon:/usr/src/botcannon:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - redis

  redis:
    build: dockerbuild/redis/.
    volumes:
      - ./db:/data/redis:rw
      - ./sockets/:/run/redis/:rw
